version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.1"
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  rabbitmq:
    image: "rabbitmq:3.7.15-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.1"
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.1.1"
    environment:
      - "COMPOSE_CONVERT_WINDOWS_PATHS=1"
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
